### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by JeromeDesseaux** [arnemolland/sigv4#1]
Hi and thanks for the work! 

I'd like to use your library but cant find an example or even understand its purpose. Could you provide some code in order to use it properly? Thanks :)

**Comment by igoralves1** [comment]
@JeromeDesseaux  did you manage to use this package? I am getting some erros.

**Comment by JeromeDesseaux** [comment]
Hi @igoralves1, 

No, I didn't. I finally made my own Amazon requester signing requests on my own. Feel free to reuse [this code](https://github.com/JeromeDesseaux/bibliochouette/blob/master/lib/amazon_api.dart)

My code is made for requesting books products by their barcode (ISBN). I think you may adapt it for your own needs. Anyway, this code is pretty straight forward and you may understand it quite easily. 

Feel free to send me another message if needed :)

**Comment by arnemolland** [comment]
Hi @igoralves1, @JeromeDesseaux 👋

Sorry for the late response. I'm rewriting parts of this library, and will add documentation and examples!

**Comment by arnemolland** [comment]
Finished API/documentation update in 4191d0f
