### ISSUE TITLE
Another problem with x-amz-content-sha256

### ISSUE THREAD

**Issue by jfrsbg** [arnemolland/sigv4#8]
Trying to make requests from s3 bucket but i got the message:

x-amz-content-sha256 must be UNSIGNED-PAYLOAD, STREAMING-AWS4-HMAC-SHA256-PAYLOAD, or a valid sha256 value

the _no_payload value on Class Sigv4Client has "STREAMING-HMAC-SHA256-PAYLOAD" and i think
its need to be "STREAMING-AWS4-HMAC-SHA256-PAYLOAD"

**Comment by arnemolland** [comment]
Hi @jfrsbg 👋

You're absolutely right, I must have missed that one.
